dist: trusty
language: node_js
sudo: false

addons:
  chrome: stable

cache:
  yarn: true
  directories:
  - $HOME/.npm
  - node_modules

branches:
  only:
  - master

node_js:
- 10

# before_install:
# - npm i -g npm@^6.0.0

# before_script:
# - npm prune

script:
- yarn test # Run regular testing and output code coverage report
- yarn clean && yarn build

after_success:
# - yarn report-coverage
- yarn semantic-release
